# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Harsh Trivedi
# Description of the Site
description: A Tech lover Inspired by Imagination
# URL of Image of the Site
site-image: https://raw.githubusercontent.com/harsh98trivedi/harsh98trivedi.github.io/master/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Harsh Trivedi, A Tech Lover, Inspired by Imagination, Techetarian, DezineWrath, Kanpur, Design, Harsh
# URL for the Image of custom Favicon
favicon-url: https://i.imgur.com/X8pSBwA.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://i.imgur.com/hqEDxWy.jpeg
# https://i.imgur.com/dIZ56RD.jpeg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: harshtrivedi@duck.com
facebook_username: harsh98trivedi
twitter_username: harsh98trivedi
instagram_username: harsh98trivedi
linkedin_username: harsh98trivedi
github_username:  harsh98trivedi
youtube_channel_id: UCS3zvA_2r1iGT7MB3NVCGAw
reddit_username: harshtrivedi
behance_username: harsh98trivedi
dribbble_username: harsh98trivedi
spotify_username: 314ihryk3edvtusti6il3oy3x5da

# Google Analytics
google-analytics: G-45C37D3GB5

# Disqus
disqus-shortname: harshtrivedi

# Name of the Author
author-name: Harsh Trivedi
# URL for the Image of the Author
author-image: https://www.github.com/harsh98trivedi.png
# 60 Words About the Author
author-about: Howdy, I'm Harsh Trivedi. I'm passionate Tech Lover Inspired by Imagination. Apart from being an ardent tech enthusiast, I love spending time on design tools and exploring open-source projects.  I enjoy tweaking and tinkering with the gadgets I own, and apart from all this, I enjoy spending my time watching content from some of my favorite creators.  Playing with new software and apps acts like dopamine for me.

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://harsh98trivedi.github.io/links/

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .DS_Store
  - Icon
