/*
 Copyright 2018 Google Inc. All Rights Reserved.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/

importScripts("https://storage.googleapis.com/workbox-cdn/releases/6.4.1/workbox-sw.js");

if (workbox) {
  console.log(`Workbox is loaded`);

  workbox.core.setCacheNameDetails({
    prefix: "echofolio-sw",
    suffix: "v1",
    precache: "precache",
    runtime: "runtime"
  });

  // Precache assets generated by Jekyll PWA plugin
  // Add fallback to empty array if manifest is not injected
  const manifest = self.__WB_MANIFEST || [];
  workbox.precaching.precacheAndRoute(manifest);

  // Cache Google Fonts Stylesheets
  workbox.routing.registerRoute(
    ({url}) => url.origin === 'https://fonts.googleapis.com',
    new workbox.strategies.StaleWhileRevalidate({
      cacheName: 'google-fonts-stylesheets',
    })
  );

  // Cache Google Fonts Webfonts
  workbox.routing.registerRoute(
    ({url}) => url.origin === 'https://fonts.gstatic.com',
    new workbox.strategies.CacheFirst({
      cacheName: 'google-fonts-webfonts',
      plugins: [
        new workbox.expiration.ExpirationPlugin({
          maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
          maxEntries: 30,
        }),
      ],
    })
  );

  // Cache Images
  workbox.routing.registerRoute(
    ({request, url}) => request.destination === 'image' && !url.hostname.includes('disqus.com') && !url.hostname.includes('viglink.com'),
    new workbox.strategies.CacheFirst({
      cacheName: 'images',
      plugins: [
        new workbox.expiration.ExpirationPlugin({
          maxEntries: 60,
          maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
        }),
      ],
    })
  );

  // Cache specific external scripts (like FontAwesome or Particles)
  workbox.routing.registerRoute(
    ({url}) => url.origin === 'https://cdn.jsdelivr.net' || url.origin === 'https://kit.fontawesome.com',
    new workbox.strategies.StaleWhileRevalidate({
        cacheName: 'external-libraries',
    })
  );

} else {
  console.log(`Workbox didn't load`);
}
